### ISSUE TITLE
Минорные правки по интерфейсу

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#15]
https://github.com/freeday-sun/Calc_project/blob/acdbadbf53dd6728e9775879065cc647f44fede5/src/main/java/com/project/calculator/api/CalculatorInterface.java#L3

1) У методов убрать модификатор public (в интерфейсах методы public  по дефолту
2) Опечатка в начвании метода - правильно "divide"

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/4cee2654e5db488259bd14e31d152390837d604f
