### ISSUE TITLE
Переименовать класс

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#16]
https://github.com/freeday-sun/Calc_project/blob/acdbadbf53dd6728e9775879065cc647f44fede5/src/main/java/com/project/calculator/internal/factory/NumberCalc.java#L8

`NumberCalc` -> `NumberCalculator`
писать нужно полностью, сокращения - первый шаг к потере читаемости

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/2a23a572182ba35e6b294c5ce302159e19065435
