### ISSUE TITLE
Перенести реализацию из пакета factory

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#17]
https://github.com/freeday-sun/Calc_project/blob/acdbadbf53dd6728e9775879065cc647f44fede5/src/main/java/com/project/calculator/internal/factory/NumberCalc.java#L8

по смыслу реализация калькулятора не должна находиться в пакете factory
нужно сделать пакет `calculators` и убрать файл туда 

У нас в данный момент есть реализация калькулятора для чисел но вполне может появиться какая-нибудь другая

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/262ec075daeea5e5ce6d8bdb85aa361a5f91f806
