### ISSUE TITLE
Поменять названия аргументов

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#18]
https://github.com/freeday-sun/Calc_project/blob/acdbadbf53dd6728e9775879065cc647f44fede5/src/main/java/com/project/calculator/internal/factory/OperationFactory.java#L4

`from` и `to` не совсем отражают смысл аргументов (больше похоже на маппинг)
нужно поменять на вменяемые (например `leftOperand` `rightOperand`)

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/361d8df7e877aed98060b725bc243f7a660e5a20
