### ISSUE TITLE
Нарушения кодстайла

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#19]
https://github.com/freeday-sun/Calc_project/blob/acdbadbf53dd6728e9775879065cc647f44fede5/src/main/java/com/project/calculator/internal/operation/DoubleOperation.java#L17

нужно соблюдать формат 
```
if (expr) {
    action;
}   
```

**Comment by ZadorozhnyiSemen** [comment]
И так во всех операциях разного типа

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/184760e30d4e86a36b32d8e2bbdf3422e86bcc33
