### ISSUE TITLE
Ограничить тип ссылки

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#2]
https://github.com/freeday-sun/Calc_project/blob/30906db854f5a31d295e02bc4cf3096e699ccc19/src/main/java/Calc.java#L4

При создании для использования лучше ограничивать тип ссылки
Сейчас мы имеем полный функционал LinkedList
но можно оставить только возможности очереди
Deque<Operation> lastOperations = new LinkedList<>();

**Comment by freeday-sun** [comment]
Поправил в https://github.com/freeday-sun/Calc_project/commit/7ea8c5d9727164bee1a46ff2b604139d5b0ebaec
