### ISSUE TITLE
Нарушение кодстайла

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#20]
https://github.com/freeday-sun/Calc_project/blob/acdbadbf53dd6728e9775879065cc647f44fede5/src/main/java/com/project/calculator/internal/operation/NumberOperationFactory.java#L9

```if (expr) action;```  
не хватает пробела

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/c343d103eaaecbf4008751db23cad042ba07d719
