### ISSUE TITLE
Вынести класс в пакет "factory" 

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#21]
https://github.com/freeday-sun/Calc_project/blob/acdbadbf53dd6728e9775879065cc647f44fede5/src/main/java/com/project/calculator/internal/operation/NumberOperationFactory.java#L5

Находится не в своем пакете (по смыслу)

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/370c0227eca69359b3967750c670fa4e42f282e7
