### ISSUE TITLE
Добавить поддержу создания операзий для Short

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#22]
https://github.com/freeday-sun/Calc_project/blob/acdbadbf53dd6728e9775879065cc647f44fede5/src/main/java/com/project/calculator/internal/operation/NumberOperationFactory.java#L12

Забыл, при работе с Short будет возвращать null

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/c343d103eaaecbf4008751db23cad042ba07d719
