### ISSUE TITLE
Подключить jacoco для мониторинга покрытия тестами

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#26]
вот плагин, нужно добавить его в проект и прогнать таску gradle:jacocoTestReport 
https://docs.gradle.org/current/userguide/jacoco_plugin.html

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/9995742149425c7e6aeff407c66b6d4771046f4c
