### ISSUE TITLE
Поправить кодстайл

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#3]
https://github.com/freeday-sun/Calc_project/blob/30906db854f5a31d295e02bc4cf3096e699ccc19/src/main/java/Calc.java#L6

много где в конце строки не хватает пробела после аргументов, нужно поправить

**Comment by freeday-sun** [comment]
Поправил в https://github.com/freeday-sun/Calc_project/commit/7ea8c5d9727164bee1a46ff2b604139d5b0ebaec
