### ISSUE TITLE
Убрать логгирование в тестах

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#5]
https://github.com/freeday-sun/Calc_project/blob/30906db854f5a31d295e02bc4cf3096e699ccc19/src/test/java/CalcTest.java#L31

System.out нужно пролностью повыпиливать из тестов

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/7ea8c5d9727164bee1a46ff2b604139d5b0ebaec
