### ISSUE TITLE
Создать структуру пакетов

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#7]
Что плохо сейчас: все файлы находятся в пакете main и выглядит все не очень структурированно
Что сделать:
1) сделать общий пакет приложения по гайдлайнам Java (напр. com.project.calculator)
2) Перенести все файлы туда
3) в пакете com.project.calculator сделать 2 пакета "api" и "internal"
4) в api пакет положить интерфейс калькулятора
5) в пакет internal положить реализацию калькулятора
6) в пакете internal сделать 3 пакета (factory, operation, storage)
7) в пакет factory положить фабрику (интерфейс и реализацию)
8) в пакет operation положить операции и операторы
9) в пакет storage положить operation manager (интерфейс и реализацию)

**Comment by freeday-sun** [comment]
Поправил в https://github.com/freeday-sun/Calc_project/commit/76f3075434d133ffb650c5ad00d73ec1a89c849e
