### ISSUE TITLE
Нужно добавить использование дженериков

### ISSUE THREAD

**Issue by ZadorozhnyiSemen** [freeday-sun/Calc_project#8]
https://github.com/freeday-sun/Calc_project/blob/4f951e0755191ccc17aa30b42d692848fa7980f9/src/main/java/ICalculator.java#L1

1) Кажется, что идея ставить "I" перед интерфейсами немного изжила себя и плохо читается
Я предлагаю убрать из интерфейсов префикс "I" "ICalculator" -> "Calculator" 
Если хочется дать понять, что это интерфейс, можно так и писать "CalculatorInterface" это будет гораздо лучше выглядеть

2) Хочется, чтобы калькулятор тоже был типизированным "Calculator\<T\>" а наша реализация была бы NumberCalculator implements Calculator\<Number\>
Мало ли что мы захотим складывать

**Comment by freeday-sun** [comment]
https://github.com/freeday-sun/Calc_project/commit/576b992b1fcc2a87d89d54d28f0c1e37f7d34bd4
